# Generated by Django 3.2.3 on 2021-06-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('mail', models.CharField(max_length=45)),
            ],
        ),
    ]
